server:
  port: 8083
 
spring:
  datasource:
    username: root
    password: root123 
    url: jdbc:mysql:///jrtp
#    driver-class-name: com.mysql.jdbc.Driver 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
  application:
    name: ED-API
  boot:
    admin:
      client:
        url: http://localhost:1111/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'  
 